stages:
    - build
    - deploy

before_script:
    - mix local.hex --force
    - mix local.rebar

variables:
    APPLICATION_NAME: astarte_pairing
    CASSANDRA_CLUSTER_NAME: astartetest

mix:test-ci:
    image: elixir:1.6.5
    services:
        - scylladb/scylla:latest
        - rabbitmq:3.6
        - ispirata/docker-alpine-cfssl-autotest:astarte
    stage: build
    script:
        - export MIX_ENV=test
        - mix deps.get
        - mix deps.compile
        - mix compile
        - mix coveralls
    except:
        - branches@Astarte-NG/astarte_pairing

mix:build:
    image: elixir:1.6.5
    services:
        - scylladb/scylla:latest
        - rabbitmq:3.6
        - ispirata/docker-alpine-cfssl-autotest:astarte
    stage: build
    script:
        - export MIX_ENV=test
        - mix deps.get
        - mix deps.compile
        - mix compile
        - mix coveralls
        - export MIX_ENV=dev
        - mix release
    only:
        - master@Astarte-NG/astarte_pairing

mix:release-build:
    image: elixir:1.6.5
    services:
        - scylladb/scylla:latest
        - rabbitmq:3.6
        - ispirata/docker-alpine-cfssl-autotest:astarte
    stage: build
    script:
        - export MIX_ENV=test
        - mix deps.get
        - mix deps.compile
        - mix compile
        - mix coveralls
        - export MIX_ENV=prod
        - mix release
    only:
        - tags@Astarte-NG/astarte_pairing

docker:snapshot-container:
    image: docker:latest
    before_script:
        - docker info
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
    services:
        - docker:stable-dind
    stage: deploy
    only:
        - master@Astarte-NG/astarte_pairing
    script:
        - docker build -t $DOCKER_REGISTRY/astarte-ng/astarte_pairing:snapshot .
        - docker push $DOCKER_REGISTRY/astarte-ng/astarte_pairing:snapshot

docker:testing-container:
    image: docker:latest
    before_script:
        - docker info
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
    services:
        - docker:stable-dind
    stage: deploy
    only:
        - testing@Astarte-NG/astarte_pairing
    script:
        - docker build -t $DOCKER_REGISTRY/astarte-ng/astarte_pairing:testing .
        - docker push $DOCKER_REGISTRY/astarte-ng/astarte_pairing:testing
