language: elixir
# Needed for Cassandra
sudo: required
services:
  - cassandra
  - rabbitmq
  - docker
before_install:
  - docker run -d -p 127.0.0.1:8888:8080 ispirata/docker-alpine-cfssl-autotest:astarte
  - docker ps -a
env:
  - CASSANDRA_DB_HOST=localhost RABBITMQ_HOST=localhost CFSSL_API_URL=http://localhost:8888 MIX_ENV=test
matrix:
  include:
    - elixir: 1.5
      otp_release: 20.2
    # Elixir 1.6 isn't currently supported due to some dependencies - re-enable in the future.
    #- elixir: 1.6
    #  otp_release: 20.2
before_script:
  # Needed or Elixir 1.6 will fail due to a non-updated index
  - ~/.mix/rebar3 update
after_script:
  - mix coveralls.travis
